server:
  port: 31001
spring:
  application:
    name: xc-service-manage-cms
  data:
    mongodb:
      uri: mongodb://root:123@localhost:27017
      database: xc_cms
  freemarker:
    cache: false # 关闭缓存模板，方便测试
    settings:
      template_update_delay: 0
  rabbitmq:
    host: 192.168.100.132
    port: 5672
    username: kangyong
    password: kangyong
    virtual-host: /