server:
  port: 31400
spring:
  application:
    name: xc-service-manage-media
  data:
    mongodb:
      uri: mongodb://root:123@localhost:27017
      database: xc_media
eureka:
  client:
    register-with-eureka: true # 服务注册开关
    fetch-registry: true # 服务发现开关
    service-url: #Eureka客户端与Eureka服务端进行交互的地址，多个中间用逗号分隔
      defaultZone: ${EUREKA_SERVER:http://localhost:50101/eureka/}
  instance:
    prefer-ip-address: true #将自己的ip地址注册到Eureka服务中
    ip-address: ${IP_ADDRESS:127.0.0.1}
    instance-id: ${spring.application.name}:${server.port} #指定实例id
ribbon:
  max-auto-retries: 2 # 最大重试次数，当Eureka中可以找到服务，但是服务连不上时将会重试
  max-auto-retries-next-server: 3 # 切换实例的重试次数
  ok-to-retry-on-all-operations: false # 对所有操作请求都进行重试，如果是get则可以
  connection-timeout: 5000 # 请求连接的超时时间
  read-timeout: 6000 # 请求处理的超时时间
xc-service-manage-media:
  upload-location: D:/data/video/